events {}

http {


    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    upstream auth_pool {
        server auth-service-1:8000;
        server auth-service-2:8000;
        server auth-service-3:8000;
    }

    upstream booking_pool {
        server booking-service-1:8000;
        server booking-service-2:8000;
        server booking-service-3:8000;
    }

    upstream hostel_pool {
        server hostel-service-1:8000;
        server hostel-service-2:8000;
        server hostel-service-3:8000;
    }

    upstream request_pool {
        server request-service-1:8000;
        server request-service-2:8000;
        server request-service-3:8000;
    }

    upstream graphql_pool {
        server graphql-gateway-1:8080;
        server graphql-gateway-2:8080;
        server graphql-gateway-3:8080;
    }
    upstream frontend_pool { server frontend:80; }


    server {
        listen 80;
        limit_req zone=api_limit burst=10 nodelay;

        # API endpoints
        location /auth/ {
            proxy_pass http://auth_pool/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /booking/ {
            proxy_pass http://booking_pool/booking/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /hostel/ {
            proxy_pass http://hostel_pool/hostel/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /request/ {
            proxy_pass http://request_pool/request/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /graphql {
            proxy_pass http://graphql_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Frontend
        location / {
            proxy_pass http://frontend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
